### ISSUE TITLE
Not operated with d3.js v4.1.0

### ISSUE THREAD

**Issue by withsmilo** [benkeen/d3pie#109]
New d3.js version(v4.1.0) maybe is not suitable to latest d3pie version(v0.1.9). :sob:

**Comment by mojoaxel** [comment]
@withsmilo What kind of error do you get?

**Comment by lyndon160** [comment]
I get this problem too. Just get various "cannot read property" errors within the d3pie.js file.

**Comment by mojoaxel** [comment]
There are breaking changes from d3@3.5.17 to [d3@4.0.0](https://github.com/d3/d3/releases/tag/v4.0.0) see [jsbin](http://jsbin.com/hurofis/2/edit?html,console,output).
D3pie needs to be updated!

**Comment by rols2015** [comment]
having the same problem with d3js V4.
TypeError: a.svg.selectAll(...).data(...).enter(...).append(...).text(...).attr(...) is null[Learn More]
I am using V4, How can i fix it? Any ideas?

**Comment by ColeDCrawford** [comment]
Use this branch - still some issues with titles, etc but it's working alright. https://github.com/benkeen/d3pie/pull/112

**Comment by benkeen** [comment]
That branch has been merged in and I've patched a few other issues. I'll release 0.2.0 this weekend.
