### ISSUE TITLE
All of the examples generate errors on the console with d3 4.2.3 (current version)

### ISSUE THREAD

**Issue by alignsoft** [benkeen/d3pie#113]
Does this work with the current version of d3? If not, are there plans to upgrade it so that it does?

I get this error on the simplest piechart example just copy/pasting the code into an html file:

Uncaught TypeError: Cannot read property 'attr' of null
addTitle @ d3pie.js:1587
_init @ d3pie.js:2059
d3pie @ d3pie.js:1915

**Comment by trentrockport** [comment]
Agree with @alignsoft that this is a serious issue. Thinking that there will need to be a (to be deprecated) version of d3pie that's compatible with version 3.x of d3 and an update that's compatible with the (completely rewritten) version 4.x of d3.

**Comment by benkeen** [comment]
Agreed, this needs to be updated. Time time time is the issue. Let me get back to you this weekend after I take a look.

**Comment by benkeen** [comment]
This is now working. I need to patch one more thing but I'll release `0.2.0` this weekend that supports the latest version of d3 (4.7.2).
