### ISSUE TITLE
Wrong percentage calculations

### ISSUE THREAD

**Issue by cunha1973** [benkeen/d3pie#122]
Even using the generator the percentage calculation goes over 100%.

![image](https://cloud.githubusercontent.com/assets/7191580/22899603/88d3647a-f212-11e6-9bd9-e14f976ad5bf.png)

**Comment by vinyasmusic** [comment]
Even I observed this just now. There seems to be an issue with use of floor or ceiling somewhere in the calculation.

**Comment by benkeen** [comment]
Thanks! I'm looking at this script this weekend to update it for compatibility with the latest version of d3. I'll look at this one too.

**Comment by benkeen** [comment]
Basically the problem is just that each rounding occurs on the segment level and doesn't take into account the other pieces. Should be pretty fixable.

**Comment by benkeen** [comment]
Just one oddity about my solution here: really the best way to get around rounding issues like this is to add decimal places. Say you're outputting integer and have data with 3 values: 1, 1 and 1. With this fix you're going to get 33%, 33% and 34%. Kinda weird, but really it's all that can be done. 

I'll get `0.2.0` out shortly containing this fix.

**Comment by vinyasmusic** [comment]
So if I give an input of 1.0, 1.0 and 1.0 
I would get 33.33% as the result ?

**Comment by benkeen** [comment]
Depending on the decimal places being displayed, you'd get something like:
33%, 33% and 34% _or_
33.3%, 33.3%, 33.4% _or_
33.33%, 33.33%, 33.34%
etc. 

But bottom line is that now with 0.2.1 it'll always add up to 100% exactly.

**Comment by vinyasmusic** [comment]
Thanks for the update.
