### ISSUE TITLE
current version is 0.2.1 but the 'npm install' version is 0.1.9, can help to update the npm lib?

### ISSUE THREAD

**Issue by ouhuiju** [benkeen/d3pie#132]
i try to add d3pie in webpack project by 'npm install', but found the current version is 0.2.1 but the 'npm install' version is 0.1.9, can help to update the npm lib? Many thanks!!!!!

e.g.  found v0.1.9 sometime can not render the chart in mobile h5 page, but v0.2.1 can, please also help to slove XD

best regards & thanks.

**Comment by benkeen** [comment]
Apologies! All fixed. :)
https://www.npmjs.com/package/d3pie
