### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by benkeen** [benkeen/d3pie#20]
It's time!

**Comment by toddwerts** [comment]
Hi, is there a reason you you decided to leave jquery as a dependency in bower.json?

Unfortunately it's a deal-breaker for my organization -- no jquery allowed. To verify it's not actually needed at runtime I manually removed the jquery dependency from my local d3pie/bower.json. It worked!

Is there a version out there with jquery removed from bower.json?

(sorry I left this comment with the issue as well...(
