### ISSUE TITLE
How open sector after load page?

### ISSUE THREAD

**Issue by chip-and-dail** [benkeen/d3pie#29]
How open sector after load page?

**Comment by benkeen** [comment]
Hey @chip-and-dail, sorry for not responding to this. To open a sector on page load, just use the `openSegment()` method, called on page load. For example, if you're using jQuery in your page you can use the `$(function() { ... });` to trigger code to execute on page load, like so:

```javascript
var myPie = new d3pie("element", { ... });

$(function() {
  myPie.openSegment(3); // opens the 4th segment
});
```

**Comment by chip-and-dail** [comment]
fast solution! :)

**Comment by JadePerle** [comment]
<img width="309" alt="2016-06-22 10 15 26" src="https://cloud.githubusercontent.com/assets/11451418/16252778/9c60de32-3863-11e6-9b7b-236674409f91.png">
@benkeen Have you ever seen any problem like this? If I want to open the segment by onload callback, it disappears!
