### ISSUE TITLE
labels.percentage.decimalPlaces is not honored & percentages are rounded to floor value

### ISSUE THREAD

**Issue by patil-nileshb** [benkeen/d3pie#49]
labels.percentage.decimalPlaces is not honored. it is always gettig percentages which are rounded to floor value that makes the total of percentages to be less than 100 in some cases

**Comment by patil-nileshb** [comment]
i do have a fix for this which i am using for my current needs & will create a pull request

**Comment by benkeen** [comment]
Thanks, @patil-nileshb!

**Comment by benkeen** [comment]
Merged as 85c4dd9c40bbbddb0968e5192dc8edfddbcc0d28
