### ISSUE TITLE
Define main assets in bower.json

### ISSUE THREAD

**Issue by waynehoover** [benkeen/d3pie#68]
I'm not to familiar with bower.json but this is the warning I get when using this with rails-assets.org

```
Post-install message from rails-assets-d3pie:
This component doesn't define main assets in bower.json.
Please open new pull request in component's repository:
http://d3pie.org/
```

**Comment by benkeen** [comment]
Thanks, @waynehoover! I just updated the file. When I roll out the next version it'll be fixed.
