### ISSUE TITLE
Charts are not working with iframes

### ISSUE THREAD

**Issue by ddeath** [benkeen/d3pie#69]
If I put element node from an iframe to the d3pie it is not working at all...

It does not pass checks for HTMLElement - problem with instanceof

and all d3pie using selectors to access elements instead of relative navigation from the provided node element.

**Comment by benkeen** [comment]
No I'm afraid that won't work. You can only target DOM nodes in the current page - not frames or iframes.  Those will need to contain their own d3pie code.
