### ISSUE TITLE
truncate labels

### ISSUE THREAD

**Issue by jasonduley** [benkeen/d3pie#71]
when I run the generator, I am not seeing the label truncation length set when I change the value from none to like 40 (the json does not change)

is there a way to set this?  thanks.

**Comment by benkeen** [comment]
Sorry about that, @jasonduley - you're quite right. There's a bug in the generation code on the website. Until it's fixed, just add the following code within your "labels" section in the generated code:

```javascript
truncation: {
	enabled: true
	length: 10
}
```

That'll truncate them to 10 chars.
