### ISSUE TITLE
Parser breaks with 'cannot read property type of undefined'

### ISSUE THREAD

**Issue by Puppala1** [benkeen/d3pie#72]
Error: Parse error using esprima for file:
 D:/BLC/Emb/emb-web/src/main/webapp/assets/js/lib/d3pie.min.js

TypeError: Cannot read property 'type' of undefined

The parser breaks with the above error message. I'm not sure what cases 'type' would be undefined.

**Comment by benkeen** [comment]
I believe this has been fixed here: https://github.com/benkeen/d3pie/pull/28

Please re-open if it's still an issue.
