### ISSUE TITLE
Error: the first d3pie() param must be a valid DOM element (not jQuery) or a ID string.

### ISSUE THREAD

**Issue by lance1572** [benkeen/d3pie#77]
I'm getting this error. 

I'm loading the scripts like this

d3.min.js
d3pie.min.js
chart.js

I'm calling like the instructions say to:
var pie = new d3pie("pieChart", {});

The weird this is this happened before and I took the code completely out recreated it again without error then it shows an error again. Thus not loading.

**Comment by neolivz** [comment]
Looks like your page does not have container with id "pieChart". Are you sure your div id is pieChart?

**Comment by Puppala1** [comment]
Yes.

**Comment by lance1572** [comment]
Sorry. No issue. It was the link to the pie script. I had used the unminified but linked to the min.

**Comment by neolivz** [comment]
@benkeen : I think you should close the issue

**Comment by lance1572** [comment]
Closed!
