### ISSUE TITLE
Tooltip remains visible

### ISSUE THREAD

**Issue by ojacquemart** [benkeen/d3pie#78]
Since 0.1.7, when tooltips are enabled, it seems like the previously shown tooltips remain visible.

It is visible on the d3pie generator:
- go to http://d3pie.org/#generator-tooltips,
- enable the tooltips.

**Comment by ojacquemart** [comment]
The issue seems introduced by #54.
0.1.6 just works fine.

**Comment by benkeen** [comment]
Drat, thanks @ojacquemart. Can't believe I missed that. Boy this project needs tests. 

I'm out of town at the moment, but as soon as I get a spare hour I'll do a patch release. Thanks!

**Comment by benkeen** [comment]
Fixed in 0.1.8.

**Comment by ojacquemart** [comment]
Thanks for the fix!

Great project, btw :+1:

**Comment by benkeen** [comment]
No problem, thanks @ojacquemart :)
