### ISSUE TITLE
This version was entered incorrectly in the d3pie.js source file.

### ISSUE THREAD

**Issue by minias** [benkeen/d3pie#99]
https://github.com/benkeen/d3pie/blob/master/d3pie/d3pie.js#L25
var _version = "0.1.6";

Thanks for open source.

**Comment by benkeen** [comment]
Thanks @minias! I'll include a fix for this in the next release.

**Comment by benkeen** [comment]
This has been updated with 0.2.0. I'll release it shortly. Thanks again!
